export const ROUTE = {
  main: '/',
  login: '/login',
  tutorial: '/tutorial',
  play: '/play',
  finder: '/play/finder',
  game: '/play/game',
  lobby: '/play/lobby',
  ranking: '/ranking',
  collection: '/collection',
  label: '/label',
  achievement: '/achievement',
  home: '/home',
  result: '/result',
  setting: '/settings',
  example: '/example',
  error: '/error',
};
