export const ROUTE = {
  main: '/',
  login: 'login',
  loading: 'loading',
  play: '/play',
  finder: '/play/finder',
  game: '/play/game',
  lobby: '/play/lobby',
  ranking: 'ranking',
  collection: 'collection',
  home: '/home',
  result: 'result',
  setting: 'settings',
  example: 'example',
  error: '/error',
  finder: '/play/finder',
  game: '/play/game',
};
